<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="..\ApexDynamics.TitanWatch.ResponseSys.Application\ApexDynamics.TitanWatch.ResponseSys.Application.csproj" />
    <ProjectReference Include="..\ApexDynamics.TitanWatch.ResponseSys.Infrastructure\ApexDynamics.TitanWatch.ResponseSys.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CoreEx.AspNetCore" />
    <PackageReference Include="CoreEx.AspNetCore.NSwag" />
    <PackageReference Include="CoreEx.Caching.FusionCache" />
    <PackageReference Include="CoreEx.Database.Postgres" />
    <PackageReference Include="Aspire.Azure.Npgsql" />
    <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Backplane.StackExchangeRedis" />
    <PackageReference Include="ZiggyCreatures.FusionCache.Serialization.SystemTextJson" />
  </ItemGroup>
  <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
</Project>
