using Microsoft.Extensions.Options;
using OpenTelemetry;
using OpenTelemetry.Trace;
using StackExchange.Redis;
using ZiggyCreatures.Caching.Fusion;
using ZiggyCreatures.Caching.Fusion.Backplane.StackExchangeRedis;
using ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Repositories;

namespace ApexDynamics.TitanWatch.ResponseSys.Api;

public class Program
{
    private static void Main(string[] args)
    {
        // Create the web builder.
        var builder = WebApplication.CreateBuilder(args);

        // Add CoreEx host settings.
        builder.AddHostSettings();

        // Add CoreEx services.
        builder.Services
            .AddPrecisionTimeProvider()
            .AddExecutionContext()
            .AddReferenceDataOrchestrator()              // Resolves the (CodeGen-generated) IReferenceDataProvider from DI at runtime — no compile-time dependency on the generated type.
            .AddMvcWebApi()
            .AddHttpWebApi();

        // Dynamically register all [ScopedService] application services and infrastructure repositories (including those generated by CodeGen) by scanning each assembly. The AssemblyMarker types are stable anchors that always exist.
        builder.Services.AddDynamicServicesUsing(typeof(ApexDynamics.TitanWatch.ResponseSys.Application.AssemblyMarker).Assembly, typeof(ApexDynamics.TitanWatch.ResponseSys.Infrastructure.AssemblyMarker).Assembly);

        // Add L1/L2 caching services.
        builder.Services.AddMemoryCache();              // Adds the in-memory cache - L1.
        builder.AddRedisDistributedCache("redis");      // Adds Redis as the distributed cache - L2.

        // Add and wire-up FusionCache including backplane.
        builder.Services.AddFusionCache()
            .WithRegisteredMemoryCache()
            .WithRegisteredDistributedCache()
            .WithBackplane(sp => new RedisBackplane(new RedisBackplaneOptions { Configuration = sp.GetRequiredService<IOptions<ConfigurationOptions>>().Value.ToString() }))
            .WithSystemTextJsonSerializer(JsonDefaults.SerializerOptions);

        // Add CoreEx caching services.
        builder.Services
            .AddFusionHybridCache()                     // Adds the CoreEx.Caching.IHybridCache for FusionCache.
            .AddDefaultCacheKeyProvider()               // Adds the default CoreEx.Caching.ICacheKeyProvider.
            .AddHybridCacheIdempotencyProvider();       // Adds the CoreEx.Caching.Idempotency.IIdempotencyProvider.

        // Add the repository and related database services.
        builder.AddNpgsqlDataSource("Postgres");        // Adds the NpgsqlDataSource (using Aspire library).
        builder.Services
            .AddPostgresDatabase()                      // Adds the PostgresDatabase.
            .AddPostgresUnitOfWork()                    // Adds the PostgresUnitOfWork for the PostgresDatabase.
            .AddEventFormatter()                        // Adds the EventFormatter to enable message formatting for publishing.
            .AddPostgresOutboxPublisher((_, c) => c.Statement = "SELECT \"responsesys\".\"fn_outbox_enqueue\"")               // Adds the PostgresOutboxPublisher as the IEventPublisher.
            .AddDbContext<ResponseSysDbContext>()       // Adds the standard EF DbContext.
            .AddEfDb<ResponseSysEfDb>();                // Adds the CoreEx extended EF service.

        // Post-configure all health-checks; adds the standard tags.
        builder.Services.PostConfigureAllHealthChecks();

        // Add the ASP.NET Core services.
        builder.Services.AddControllers();

        // Register the server-authoritative simulation engine (timer-based hosted service). Disabled under test (Simulation:Enabled=false) so the feed stays deterministic.
        if (builder.Configuration.GetValue("Simulation:Enabled", true))
            builder.Services.AddHostedService<SimulationHostedService>();

        // Add the OpenAPI services.
        builder.Services.AddOpenApiDocument(s =>
        {
            s.Title = builder.Environment.ApplicationName;
            s.AddCoreExConfiguration();
        });

        // Add OpenTelemetry tracing.
        builder.WithCoreExTelemetry()
            .WithCoreExPostgresTelemetry()
            .UseOtlpExporter();

        // Build the application.
        var app = builder.Build();

        // Configure the pipeline/middleware (order is important).
        app.UseCoreExExceptionHandler();
        app.UseHttpsRedirection();
        // app.UseAuthentication();   // TODO: register an authentication scheme (builder.Services.AddAuthentication(...)) then uncomment.
        app.UseAuthorization();
        app.UseExecutionContext();
        app.UseIdempotencyKey();
        app.MapControllers();
        app.MapHostedServices();   // Exposes /hosted-services/{name}/pause|resume|status management endpoints for the simulation engine.

        app.UseOpenApi();
        app.UseSwaggerUi();
        app.MapHealthChecks(/* detailedGroupConfigure: g => g.RequireAuthorization() */);   // Detailed endpoints expose diagnostics and must be secured; basic live/startup/ready checks stay anonymous for orchestrator probes.

        // Run the application.
        app.Run();
    }
}
