// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Application;

/// <summary>Provides the <see cref="IReferenceDataProvider"/> implementation.</summary>
[ScopedService<IReferenceDataProvider>]
public partial class ReferenceDataService(IReferenceDataRepository repository) : IReferenceDataProvider
{
    private readonly IReferenceDataRepository _repository = repository.ThrowIfNull();

    /// <inheritdoc/>
    public IEnumerable<(Type, Type)> Types =>
    [
        (typeof(ThreatLevel), typeof(ThreatLevelCollection)),
        (typeof(LeviathanStatus), typeof(LeviathanStatusCollection)),
        (typeof(SignalSeverity), typeof(SignalSeverityCollection)),
    ];

    /// <inheritdoc/>
    public virtual async Task<IReferenceDataCollection> GetAsync(Type type, CancellationToken cancellationToken = default) => type switch
    {
        _ when type == typeof(ThreatLevel) => await _repository.GetAllThreatLevelsAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(LeviathanStatus) => await _repository.GetAllLeviathanStatusesAsync(cancellationToken).ConfigureAwait(false),
        _ when type == typeof(SignalSeverity) => await _repository.GetAllSignalSeveritiesAsync(cancellationToken).ConfigureAwait(false),
        _ => throw new InvalidOperationException($"Type {type.FullName} is not a known {nameof(IReferenceData)}.")
    };
}

#nullable restore