// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Application.Repositories;

/// <summary>Enables the underlying reference-data repository.</summary>
public partial interface IReferenceDataRepository
{
    /// <summary>Gets all <see cref="ThreatLevel"/> items.</summary>
    /// <returns>The <see cref="ThreatLevelCollection"/>.</returns>
    Task<ThreatLevelCollection> GetAllThreatLevelsAsync(CancellationToken cancellationToken = default);

    /// <summary>Gets all <see cref="LeviathanStatus"/> items.</summary>
    /// <returns>The <see cref="LeviathanStatusCollection"/>.</returns>
    Task<LeviathanStatusCollection> GetAllLeviathanStatusesAsync(CancellationToken cancellationToken = default);

    /// <summary>Gets all <see cref="SignalSeverity"/> items.</summary>
    /// <returns>The <see cref="SignalSeverityCollection"/>.</returns>
    Task<SignalSeverityCollection> GetAllSignalSeveritiesAsync(CancellationToken cancellationToken = default);
}
    
#nullable restore