// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Persistence.LeviathanStatus"/> to <see cref="Contracts.LeviathanStatus"/>.</summary>
internal partial class LeviathanStatusMapper : Mapper<Persistence.LeviathanStatus, Contracts.LeviathanStatus, LeviathanStatusMapper>
{
    /// <inheritdoc/>
    protected override Contracts.LeviathanStatus OnMap(Persistence.LeviathanStatus source)
    {
        var destination = new Contracts.LeviathanStatus
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <see cref="OnMap" /> method.</summary>
    partial void OnMapExtend(Persistence.LeviathanStatus source, Contracts.LeviathanStatus destination);
}

#nullable restore