// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Persistence.SignalSeverity"/> to <see cref="Contracts.SignalSeverity"/>.</summary>
internal partial class SignalSeverityMapper : Mapper<Persistence.SignalSeverity, Contracts.SignalSeverity, SignalSeverityMapper>
{
    /// <inheritdoc/>
    protected override Contracts.SignalSeverity OnMap(Persistence.SignalSeverity source)
    {
        var destination = new Contracts.SignalSeverity
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <see cref="OnMap" /> method.</summary>
    partial void OnMapExtend(Persistence.SignalSeverity source, Contracts.SignalSeverity destination);
}

#nullable restore