// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Mapping;

/// <summary>Provides mapping from <see cref="Persistence.ThreatLevel"/> to <see cref="Contracts.ThreatLevel"/>.</summary>
internal partial class ThreatLevelMapper : Mapper<Persistence.ThreatLevel, Contracts.ThreatLevel, ThreatLevelMapper>
{
    /// <inheritdoc/>
    protected override Contracts.ThreatLevel OnMap(Persistence.ThreatLevel source)
    {
        var destination = new Contracts.ThreatLevel
        {
            Id = source.Id!,
            Code = source.Code,
            Text = source.Text,
            Description = source.Description,
            SortOrder = source.SortOrder,
            IsInactive = !source.IsActive,
            StartsOn = source.StartsOn,
            EndsOn = source.EndsOn,
            ETag = source.ETag,
            Color = source.Color
        };

        OnMapExtend(source, destination);
        return destination;
    }

    /// <summary>Provides the opportunity to extend the <see cref="OnMap" /> method.</summary>
    partial void OnMapExtend(Persistence.ThreatLevel source, Contracts.ThreatLevel destination);
}

#nullable restore