// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Api.Controllers;

/// <summary>Represents the reference-data controller.</summary>
[ApiController, Route("/api/refdata")]
public partial class ReferenceDataController(CoreEx.AspNetCore.Mvc.WebApi webApi) : ControllerBase
{
    private readonly CoreEx.AspNetCore.Mvc.WebApi _webApi = webApi.ThrowIfNull();

    private static readonly DataMap<string> _mapper = new(StringComparer.OrdinalIgnoreCase)
    {
        { "threat-levels", nameof(ThreatLevel) },
        { "leviathan-statuses", nameof(LeviathanStatus) },
        { "signal-severities", nameof(SignalSeverity) }
    };

    [HttpGet("threat-levels"), HttpHead("threat-levels")]
    [ProducesResponseType(typeof(ThreatLevel[]), 200)]
    public Task<IActionResult> GetThreatLevelsAsync([FromQuery] IEnumerable<string>? codes = default, string? text = default)
        => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetWithFilterAsync<ThreatLevel>(codes, text, ro.IsIncludeInactive, ct));

    [HttpGet("leviathan-statuses"), HttpHead("leviathan-statuses")]
    [ProducesResponseType(typeof(LeviathanStatus[]), 200)]
    public Task<IActionResult> GetLeviathanStatusesAsync([FromQuery] IEnumerable<string>? codes = default, string? text = default)
        => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetWithFilterAsync<LeviathanStatus>(codes, text, ro.IsIncludeInactive, ct));

    [HttpGet("signal-severities"), HttpHead("signal-severities")]
    [ProducesResponseType(typeof(SignalSeverity[]), 200)]
    public Task<IActionResult> GetSignalSeveritiesAsync([FromQuery] IEnumerable<string>? codes = default, string? text = default)
        => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetWithFilterAsync<SignalSeverity>(codes, text, ro.IsIncludeInactive, ct));

    [HttpGet]
    [ProducesResponseType(typeof(ReferenceDataMultiDictionary), 200)]
    public Task<IActionResult> GetNamedAsync([FromQuery] string[] name)
        => _webApi.GetAsync(Request, (ro, ct) => ReferenceDataOrchestrator.Current.GetNamedAsync(name, ro.IsIncludeInactive, _mapper, ct));
}

#nullable restore