// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Repositories;

/// <summary>Provides the underlying reference-data repository.</summary>
[ScopedService<IReferenceDataRepository>]
public partial class ReferenceDataRepository : IReferenceDataRepository
{
    /// <inheritdoc/>
    public Task<Contracts.ThreatLevelCollection> GetAllThreatLevelsAsync(CancellationToken cancellationToken = default)
        => _ef.ThrowIfNull().Model<Persistence.ThreatLevel>().Query().ToMappedItemsAsync<Persistence.ThreatLevel, Contracts.ThreatLevelCollection, Contracts.ThreatLevel>(ThreatLevelMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.LeviathanStatusCollection> GetAllLeviathanStatusesAsync(CancellationToken cancellationToken = default)
        => _ef.ThrowIfNull().Model<Persistence.LeviathanStatus>().Query().ToMappedItemsAsync<Persistence.LeviathanStatus, Contracts.LeviathanStatusCollection, Contracts.LeviathanStatus>(LeviathanStatusMapper.Map, cancellationToken);

    /// <inheritdoc/>
    public Task<Contracts.SignalSeverityCollection> GetAllSignalSeveritiesAsync(CancellationToken cancellationToken = default)
        => _ef.ThrowIfNull().Model<Persistence.SignalSeverity>().Query().ToMappedItemsAsync<Persistence.SignalSeverity, Contracts.SignalSeverityCollection, Contracts.SignalSeverity>(SignalSeverityMapper.Map, cancellationToken);
}

#nullable restore