// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.Database'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Repositories;

public partial class ResponseSysDbContext
{
    /// <summary>Adds the generated models to the <paramref name="modelBuilder"/>.</summary>
    /// <param name="modelBuilder">The <see cref="Microsoft.EntityFrameworkCore.ModelBuilder"/>.</param>
    partial void AddGeneratedModels(Microsoft.EntityFrameworkCore.ModelBuilder modelBuilder)
    {
        // Add the entity/model configuration for the "responsesys"."threat_level" database table.
        modelBuilder.Entity<ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence.ThreatLevel>(e =>
        {
            e.ToTable("threat_level", "responsesys");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("threat_level_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.Color).HasColumnName("color").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "responsesys"."leviathan_status" database table.
        modelBuilder.Entity<ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence.LeviathanStatus>(e =>
        {
            e.ToTable("leviathan_status", "responsesys");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("leviathan_status_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "responsesys"."signal_severity" database table.
        modelBuilder.Entity<ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence.SignalSeverity>(e =>
        {
            e.ToTable("signal_severity", "responsesys");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("signal_severity_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Code).HasColumnName("code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Text).HasColumnName("text").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.IsActive).HasColumnName("is_active").HasColumnType("BOOLEAN");
            e.Property(p => p.SortOrder).HasColumnName("sort_order").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Ignore(p => p.Description).Ignore(p => p.StartsOn).Ignore(p => p.EndsOn);
        });

        // Add the entity/model configuration for the "responsesys"."leviathan" database table.
        modelBuilder.Entity<ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence.Leviathan>(e =>
        {
            e.ToTable("leviathan", "responsesys");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("leviathan_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Codename).HasColumnName("codename").HasColumnType("CHARACTER VARYING(100)");
            e.Property(p => p.ClassNumeral).HasColumnName("class_numeral").HasColumnType("CHARACTER VARYING(10)");
            e.Property(p => p.Archetype).HasColumnName("archetype").HasColumnType("CHARACTER VARYING(100)");
            e.Property(p => p.Range).HasColumnName("range").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.Height).HasColumnName("height").HasColumnType("INTEGER");
            e.Property(p => p.Speed).HasColumnName("speed").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.Hp).HasColumnName("hp").HasColumnType("INTEGER");
            e.Property(p => p.HpMax).HasColumnName("hp_max").HasColumnType("INTEGER");
            e.Property(p => p.StatusCode).HasColumnName("status_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Lng).HasColumnName("lng").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.Lat).HasColumnName("lat").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.ThreatCode).HasColumnName("threat_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Heading).HasColumnName("heading").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.FromLng).HasColumnName("from_lng").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.FromLat).HasColumnName("from_lat").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.ToLng).HasColumnName("to_lng").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.ToLat).HasColumnName("to_lat").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.Target).HasColumnName("target").HasColumnType("CHARACTER VARYING(100)");
            e.Property(p => p.StartRange).HasColumnName("start_range").HasColumnType("INTEGER");
            e.Property(p => p.Repel).HasColumnName("repel").HasColumnType("DOUBLE PRECISION");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
            e.Property(p => p.IsDeleted).HasColumnName("is_deleted").HasColumnType("BOOLEAN");
        });

        // Add the entity/model configuration for the "responsesys"."signal_event" database table.
        modelBuilder.Entity<ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence.SignalEvent>(e =>
        {
            e.ToTable("signal_event", "responsesys");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("signal_event_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.SeverityCode).HasColumnName("severity_code").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Message).HasColumnName("message").HasColumnType("CHARACTER VARYING(500)");
            e.Property(p => p.Timestamp).HasColumnName("timestamp").HasColumnType("BIGINT");
            e.Property(p => p.LeviathanId).HasColumnName("leviathan_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
        });

        // Add the entity/model configuration for the "responsesys"."dispatch_unit" database table.
        modelBuilder.Entity<ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence.DispatchUnit>(e =>
        {
            e.ToTable("dispatch_unit", "responsesys");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("dispatch_unit_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Name).HasColumnName("name").HasColumnType("CHARACTER VARYING(100)");
            e.Property(p => p.Available).HasColumnName("available").HasColumnType("INTEGER");
            e.Property(p => p.Capacity).HasColumnName("capacity").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
        });

        // Add the entity/model configuration for the "responsesys"."last_stand_city" database table.
        modelBuilder.Entity<ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence.LastStandCity>(e =>
        {
            e.ToTable("last_stand_city", "responsesys");
            e.HasKey(p => p.Id);
            e.Property(p => p.Id).HasColumnName("last_stand_city_id").HasColumnType("CHARACTER VARYING(50)");
            e.Property(p => p.Name).HasColumnName("name").HasColumnType("CHARACTER VARYING(100)");
            e.Property(p => p.Side).HasColumnName("side").HasColumnType("CHARACTER VARYING(10)");
            e.Property(p => p.Population).HasColumnName("population").HasColumnType("INTEGER");
            e.Property(p => p.CreatedBy).HasColumnName("created_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.CreatedOn).HasColumnName("created_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.UpdatedBy).HasColumnName("updated_by").HasColumnType("CHARACTER VARYING(250)");
            e.Property(p => p.UpdatedOn).HasColumnName("updated_on").HasColumnType("TIMESTAMP WITH TIME ZONE");
            e.Property(p => p.ETag).HasColumnName("xmin").HasColumnType("XID").IsRowVersion().HasConversion(ValueConverterBridge.Create<string?, uint>(BaseDatabase.RowVersionConverter));
        });
    }
}

#nullable restore