// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.Database'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence;

/// <summary>Persistence model representing the '<c>"responsesys"."dispatch_unit"</c>' database table.</summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>dispatch_unit_id</c>' (type '<c>CHARACTER VARYING(50)</c>').</remarks>
public partial class DispatchUnit : ModelBase<string>
{
    /// <summary>Gets or sets the value of the '<c>name</c>' column (type '<c>CHARACTER VARYING(100)</c>').</summary>
    public string Name { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>available</c>' column (type '<c>INTEGER NULL</c>').</summary>
    public int? Available { get; set; }

    /// <summary>Gets or sets the value of the '<c>capacity</c>' column (type '<c>INTEGER NULL</c>').</summary>
    public int? Capacity { get; set; }
}

#nullable restore