// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.Database'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence;

/// <summary>Persistence model representing the '<c>"responsesys"."last_stand_city"</c>' database table.</summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>last_stand_city_id</c>' (type '<c>CHARACTER VARYING(50)</c>').</remarks>
public partial class LastStandCity : ModelBase<string>
{
    /// <summary>Gets or sets the value of the '<c>name</c>' column (type '<c>CHARACTER VARYING(100)</c>').</summary>
    public string Name { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>side</c>' column (type '<c>CHARACTER VARYING(10) NULL</c>').</summary>
    public string? Side { get; set; }

    /// <summary>Gets or sets the value of the '<c>population</c>' column (type '<c>INTEGER NULL</c>').</summary>
    public int? Population { get; set; }
}

#nullable restore