// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.Database'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence;

/// <summary>Persistence model representing the '<c>"responsesys"."leviathan"</c>' database table.</summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>leviathan_id</c>' (type '<c>CHARACTER VARYING(50)</c>').</remarks>
public partial class Leviathan : ModelBase<string>, ILogicallyDeleted
{
    /// <summary>Gets or sets the value of the '<c>codename</c>' column (type '<c>CHARACTER VARYING(100)</c>').</summary>
    public string Codename { get; set; } = default!;

    /// <summary>Gets or sets the value of the '<c>class_numeral</c>' column (type '<c>CHARACTER VARYING(10) NULL</c>').</summary>
    public string? ClassNumeral { get; set; }

    /// <summary>Gets or sets the value of the '<c>archetype</c>' column (type '<c>CHARACTER VARYING(100) NULL</c>').</summary>
    public string? Archetype { get; set; }

    /// <summary>Gets or sets the value of the '<c>range</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? Range { get; set; }

    /// <summary>Gets or sets the value of the '<c>height</c>' column (type '<c>INTEGER NULL</c>').</summary>
    public int? Height { get; set; }

    /// <summary>Gets or sets the value of the '<c>speed</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? Speed { get; set; }

    /// <summary>Gets or sets the value of the '<c>hp</c>' column (type '<c>INTEGER NULL</c>').</summary>
    public int? Hp { get; set; }

    /// <summary>Gets or sets the value of the '<c>hp_max</c>' column (type '<c>INTEGER NULL</c>').</summary>
    public int? HpMax { get; set; }

    /// <summary>Gets or sets the value of the '<c>status_code</c>' column (type '<c>CHARACTER VARYING(50) NULL</c>').</summary>
    public string? StatusCode { get; set; }

    /// <summary>Gets or sets the value of the '<c>lng</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? Lng { get; set; }

    /// <summary>Gets or sets the value of the '<c>lat</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? Lat { get; set; }

    /// <summary>Gets or sets the value of the '<c>threat_code</c>' column (type '<c>CHARACTER VARYING(50) NULL</c>').</summary>
    public string? ThreatCode { get; set; }

    /// <summary>Gets or sets the value of the '<c>heading</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? Heading { get; set; }

    /// <summary>Gets or sets the value of the '<c>from_lng</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? FromLng { get; set; }

    /// <summary>Gets or sets the value of the '<c>from_lat</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? FromLat { get; set; }

    /// <summary>Gets or sets the value of the '<c>to_lng</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? ToLng { get; set; }

    /// <summary>Gets or sets the value of the '<c>to_lat</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? ToLat { get; set; }

    /// <summary>Gets or sets the value of the '<c>target</c>' column (type '<c>CHARACTER VARYING(100) NULL</c>').</summary>
    public string? Target { get; set; }

    /// <summary>Gets or sets the value of the '<c>start_range</c>' column (type '<c>INTEGER NULL</c>').</summary>
    public int? StartRange { get; set; }

    /// <summary>Gets or sets the value of the '<c>repel</c>' column (type '<c>DOUBLE PRECISION NULL</c>').</summary>
    public double? Repel { get; set; }

    /// <summary>Gets or sets the value of the '<c>is_deleted</c>' column (type '<c>BOOLEAN</c>'); see <see cref="ILogicallyDeleted.IsDeleted"/>.</summary>
    public bool IsDeleted { get; set; }
}

#nullable restore