// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.Database'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence;

/// <summary>Persistence reference-data model representing the '<c>"responsesys"."leviathan_status"</c>' database table.</summary>
public partial class LeviathanStatus : ReferenceDataModelBase<string> { }

#nullable restore