// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.Database'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence;

/// <summary>Persistence model representing the '<c>"responsesys"."signal_event"</c>' database table.</summary>
/// <remarks>The <see cref="Id"/> primary key column is '<c>signal_event_id</c>' (type '<c>CHARACTER VARYING(50)</c>').</remarks>
public partial class SignalEvent : ModelBase<string>
{
    /// <summary>Gets or sets the value of the '<c>severity_code</c>' column (type '<c>CHARACTER VARYING(50) NULL</c>').</summary>
    public string? SeverityCode { get; set; }

    /// <summary>Gets or sets the value of the '<c>message</c>' column (type '<c>CHARACTER VARYING(500) NULL</c>').</summary>
    public string? Message { get; set; }

    /// <summary>Gets or sets the value of the '<c>timestamp</c>' column (type '<c>BIGINT NULL</c>').</summary>
    public long? Timestamp { get; set; }

    /// <summary>Gets or sets the value of the '<c>leviathan_id</c>' column (type '<c>CHARACTER VARYING(50) NULL</c>').</summary>
    public string? LeviathanId { get; set; }
}

#nullable restore