// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.Database'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Infrastructure.Persistence;

/// <summary>Persistence reference-data model representing the '<c>"responsesys"."threat_level"</c>' database table.</summary>
public partial class ThreatLevel : ReferenceDataModelBase<string>
{
    /// <summary>Gets or sets the value of the '<c>color</c>' column (type '<c>CHARACTER VARYING(50) NULL</c>').</summary>
    public string? Color { get; set; }
}

#nullable restore