// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Contracts;

/// <summary>Represents the 'Leviathan Status' reference-data contract.</summary>
[ReferenceData]
public partial class LeviathanStatus : ReferenceData<LeviathanStatus> { }

/// <summary>
/// Represents the 'LeviathanStatus' reference-data contract collection.
/// </summary>
public partial class LeviathanStatusCollection() : ReferenceDataCollection<LeviathanStatus>(ReferenceDataSortOrder.Code) { }

#nullable restore