// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Contracts;

/// <summary>Represents the 'Signal Severity' reference-data contract.</summary>
[ReferenceData]
public partial class SignalSeverity : ReferenceData<SignalSeverity> { }

/// <summary>
/// Represents the 'SignalSeverity' reference-data contract collection.
/// </summary>
public partial class SignalSeverityCollection() : ReferenceDataCollection<SignalSeverity>(ReferenceDataSortOrder.Code) { }

#nullable restore