// <auto-generated/>

/*
 * This file is automatically generated by 'ApexDynamics.TitanWatch.ResponseSys.CodeGen'; any changes will be lost.
 */

#nullable enable

namespace ApexDynamics.TitanWatch.ResponseSys.Contracts;

/// <summary>Represents the 'Threat Level' reference-data contract.</summary>
[ReferenceData]
public partial class ThreatLevel : ReferenceData<ThreatLevel> 
{
    /// <summary>Gets or initializes the Color.</summary>
    public string Color { get; init; } = default!;
}

/// <summary>
/// Represents the 'ThreatLevel' reference-data contract collection.
/// </summary>
public partial class ThreatLevelCollection() : ReferenceDataCollection<ThreatLevel>(ReferenceDataSortOrder.Code) { }

#nullable restore