<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="NUnit" />
    <PackageReference Include="UnitTestEx.NUnit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\tools\ApexDynamics.TitanWatch.ResponseSys.Database\ApexDynamics.TitanWatch.ResponseSys.Database.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Data\**\*" />
  </ItemGroup>
</Project>
